### ISSUE TITLE
Adding warlock to the classlist

### ISSUE THREAD

**Issue by Geowall13** [torstorruste/PerformanceTracking#2]
Warlock is missing from the lists of classes.

The are also missing two of their defensives:
- Mortal Coil
- Dark Pact

Dark pact sacrifices some health, to give them a shield. It should probably only "count", if the final absorb value from the shield exceeds the sacrificed health.

**Comment by torstorruste** [comment]
Added mortal coil to consumables (since it's a heal), and dark pact to defensives.
