### ISSUE TITLE
Hunter issues

### ISSUE THREAD

**Issue by Geowall13** [torstorruste/PerformanceTracking#5]
Exhilaration (Hunter defensive) is not showing any numbers for any of the hunters (And I don't believe they are that bad!). This is possibly due to a spelling mistake, as it is spelled "Exhilaration", but on the performance page, it is spelled "Exhiliration".

Name: Exhilaration
ID: 109304

It would also be useful to track Feign death usages, when the conduit "Resilience of the hunter" is equipped, as that adds a DR buff for a few seconds after use. Alternatively, you could just track the buff. 

Name: Feign Death
ID: 5384

Buff name: Resilience of the Hunter
ID: 339461

**Comment by torstorruste** [comment]
The text is just for show. I use the ability ids to track what happens. The issue with Exhilaration was that it's a heal and not a buff, like the other defensives I was trakcing. I moved it over to consumables, which is where I track the heals, and added tracking for the Resilience of the Hunter buff.
